/* Replace this demo array with your full story list. Keep the variable name Storys. */
const Storys = [
  {
    Name: "The Forgotten Kingdom",
    Genres: ["Fantasy", "Adventure", "Drama"],
    Description: "The Forgotten Kingdom is a fantasy adventure about three heroes who enter a lost underwater kingdom in search of healing, redemption, and forgotten power. Along the way, they must solve magical trials, uncover buried memories, and confront the dangerous Mindseer at the heart of the legend.",
    Logo: "assets/stories/the_forgotten_kingdom/logo_black.svg",
    Wallpaper: "assets/stories/the_forgotten_kingdom/wallpaper.svg",
    Pdfstory: "assets/stories/the_forgotten_kingdom/pdf.pdf",
    Epub: "assets/stories/the_forgotten_kingdom/Etenral Ones_ The City Of Roanina, The - Kyle Young.epub",
    Ebookcover: "assets/stories/the_forgotten_kingdom/bookcover.png",
    Worddoc: "assets/stories/the_forgotten_kingdom/ebook.docx",
    Gif: "assets/stories/the_forgotten_kingdom/ebookvid.webm",
    Series: "Elseworlds",
    StoryType: "ShortStory",
    ReleaseDate: "2026-06-23"
  },
  {
    Name: "The Old Man At The Bar",
    Genres: ["Fantasy", "Sci-Fi", "Drama"],
    Description: "Some of the Ertenral Ones make a deal to watch over a village, giving a wish to a person of a true heart.",
    Logo: "assets/stories/the_old_man_at_the_bar/logo_black.svg",
    Wallpaper: "assets/stories/the_old_man_at_the_bar/wallpaper.svg",
    Pdfstory: "assets/stories/the_old_man_at_the_bar/pdf.pdf",
    Epub: "assets/stories/the_old_man_at_the_bar/The Old Man At The Bar - Kyle Young.epub",
    Ebookcover: "assets/stories/the_old_man_at_the_bar/bookcover.png",
    Gif: "assets/stories/the_old_man_at_the_bar/ebookvid.webm",
    Series: "Elseworlds",
    Worddoc: "assets/stories/the_old_man_at_the_bar/ebook.docx",
    StoryType: "ShortStory",
    ReleaseDate: "2025-01-23"
  },
  {
    Name: "The Puzzle And The Dragon",
    Genres: ["Fantasy", "Sci-Fi", "Drama"],
    Description: "Some of the Ertenral Ones make a deal to watch over a village, giving a wish to a person of a true heart.",
    Logo: "assets/stories/the_puzzle_and_the_dragon/logo_black.svg",
    Wallpaper: "assets/stories/the_puzzle_and_the_dragon/wallpaper.svg",
    Pdfstory: "assets/stories/the_puzzle_and_the_dragon/pdf.pdf",
    Epub: "assets/stories/the_puzzle_and_the_dragon/The Puzzle And The Dragon - Kyle Young.epub",
    Ebookcover: "assets/stories/the_puzzle_and_the_dragon/bookcover.png",
    Gif: "assets/stories/the_puzzle_and_the_dragon/ebookvid.webm",
    Series: "Elseworlds",
    Worddoc: "assets/stories/the_puzzle_and_the_dragon/ebook.docx",
    StoryType: "ShortStory",
    ReleaseDate: "2025-01-23"
  },
  {
    Name: "The Secret Of Owen Taylor A Dreamer Story",
    Genres: ["Fantasy", "Sci-Fi", "Drama"],
    Description: "Some of the Ertenral Ones make a deal to watch over a village, giving a wish to a person of a true heart.",
    Logo: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/logo_black.svg",
    Wallpaper: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/wallpaper.svg",
    Pdfstory: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/pdf.pdf",
    Epub: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/The Secret Of Owen Taylor_ A Dreamer Story - Kyle Young",
    Ebookcover: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/bookcover.png",
    Gif: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/ebookvid.webm",
    Series: "A Dreamer Story",
    Worddoc: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/ebook.docx",
    StoryType: "ShortStory",
    ReleaseDate: "2025-01-23"
  },
  {
    Name: "The Last Prank Of Tomist",
    Genres: ["Fantasy", "Sci-Fi", "Drama"],
    Description: "Some of the Ertenral Ones make a deal to watch over a village, giving a wish to a person of a true heart.",
    Logo: "assets/stories/the_last_prank_of_tomist/logo_black.svg",
    Wallpaper: "assets/stories/the_last_prank_of_tomist/wallpaper.svg",
    Pdfstory: "assets/stories/the_last_prank_of_tomist/pdf.pdf",
    Epub: "assets/stories/the_last_prank_of_tomist/The Last Prank of Tomist - Kyle Young",
    Ebookcover: "assets/stories/the_last_prank_of_tomist/bookcover.png",
    Gif: "assets/stories/the_last_prank_of_tomist/ebookvid.webm",
    Series: "Elseworlds",
    Worddoc: "assets/stories/the_last_prank_of_tomist/ebook.docx",
    StoryType: "ShortStory",
    ReleaseDate: "2025-01-23"
  },
  {
    Name: "The Interrogation",
    Genres: ["Fantasy", "Sci-Fi", "Drama"],
    Description: "Some of the Ertenral Ones make a deal to watch over a village, giving a wish to a person of a true heart.",
    Logo: "assets/stories/the_interrogation/logo_black.svg",
    Wallpaper: "assets/stories/the_interrogation/wallpaper.svg",
    Pdfstory: "assets/stories/the_interrogation/pdf.pdf",
    Epub: "assets/stories/the_interrogation/The Interrogation - Kyle Young.epub",
    Ebookcover: "assets/stories/the_interrogation/bookcover.png",
    Gif: "assets/stories/the_interrogation/ebookvid.webm",
    Series: "The Ertenral Ones",
    Worddoc: "assets/stories/the_interrogation/ebook.docx",
    StoryType: "ShortStory",
    ReleaseDate: "2025-01-23"
  },
  {
    Name: "The City Of Roanina",
    Genres: ["Fantasy", "Sci-Fi", "Drama"],
    Description: "Some of the Ertenral Ones make a deal to watch over a village, giving a wish to a person of a true heart.",
    Logo: "assets/stories/the_ertenral_ones_the_city_of_roanina/logo_black.svg",
    Wallpaper: "assets/stories/the_ertenral_ones_the_city_of_roanina/wallpaper.svg",
    Pdfstory: "assets/stories/the_ertenral_ones_the_city_of_roanina/pdf.pdf",
    Epub: "assets/stories/the_ertenral_ones_the_city_of_roanina/Etenral Ones_ The City Of Roanina, The - Kyle Young.epub",
    Ebookcover: "assets/stories/the_ertenral_ones_the_city_of_roanina/bookcover.png",
    Gif: "assets/stories/the_ertenral_ones_the_city_of_roanina/ebookvid.webm",
    Series: "The Ertenral Ones",
    Worddoc: "assets/stories/the_ertenral_ones_the_city_of_roanina/ebook.docx",
    StoryType: "ShortStory",
    ReleaseDate: "2025-01-23"
  }
];
