const Storys = [
	  {//Paradox: The Traveller: Chapter 1
	    Name: "The Traveller: Chapter 1: Echoes of a Kingdom",
        storytype: "Pages 57 • Books",
        LogoPostions: "Top",
        Genres: ["Fantasy", "Sci-Fi", "Myststery"],
        Forefront: "assets/stories/paradox_the_traveller/poster.png",
        Background: "assets/stories/paradox_the_traveller/background.png",
        LogoStyle1: "assets/stories/paradox_the_traveller/logo_black.svg",
        LogoStyle2: "assets/stories/paradox_the_traveller/logo_white.svg",
        LogoStyle3: "assets/stories/paradox_the_traveller/logo_blue.svg",
        LogoStyle4: "assets/stories/paradox_the_traveller/logo_red.svg",
        LogoStyle5: "assets/stories/paradox_the_traveller/logo_green.svg",
        TitleText: "Read The First Chapter In Paradox The Traveller",
        SmallText: "In a fusion of destinies and mystical quests, Noah, known as ‘The Traveler,’ embarks on a perilous journey through time in search of magical elements essential for mastering the forces of creation. Alongside him, Joshua, an assassin from the future, grapples with his broken past and the haunting memories that threaten to overshadow his lethal skills. Meanwhile, Edward confronts the loss of his magical prowess and navigates his new existence as a dragon, a form both powerful and alien to him. These three extraordinary characters, each dealing with their own set of challenges, find their fates intertwined as they navigate the complexities of loyalty, power, and identity in a multiverse orchestrated by unseen forces. Together, they face an uncertain future, their paths marked by trials of magic, betrayal, and redemption.",
        LandscapeImage: "assets/stories/paradox_the_traveller/background.png",
        Pdfstory: "assets/stories/paradox_the_traveller/pdf.pdf",
        Epub: "assets/stories/paradox_the_traveller/Paradox The Traveller Chapter 1 - Kyle Young.epub",
		Series: "Paradox",
        StoryText: ``,
		StoryExcel: "https://script.google.com/macros/s/AKfycbzdsM_WqOTon_p2LOISYtXJxKMDhG3_DLCU4ZBGIRli7DYl3d8U938Rvrp0g64LdW-D/exec",
		ReleaseDate: '2025-03-23',
	  },
	  {//The Old Man At The Bar
        Name: "The Old Man At The Bar",
        storytype: "Pages 9 • Short",
        LogoPostions: "Top",
        Genres: ["Dark", "Thriller", "Fantasy", "Myststery"],
        Forefront: "assets/stories/the_old_man_at_the_bar/poster.png",
        Background: "assets/stories/the_old_man_at_the_bar/background.png",
        LogoStyle1: "assets/stories/the_old_man_at_the_bar/logo_black.svg",
        LogoStyle2: "assets/stories/the_old_man_at_the_bar/logo_white.svg",
        LogoStyle3: "assets/stories/the_old_man_at_the_bar/logo_blue.svg",
        LogoStyle4: "assets/stories/the_old_man_at_the_bar/logo_red.svg",
        LogoStyle5: "assets/stories/the_old_man_at_the_bar/logo_green.svg",
        TitleText: "What the Story is about",
        SmallText: "When Mans Loses His Family, He Struggles To FInd A Way Forward.",
        LandscapeImage: "assets/stories/the_old_man_at_the_bar/background.png",
        Pdfstory: "assets/stories/the_old_man_at_the_bar/pdf.pdf",
        Epub: "assets/stories/the_old_man_at_the_bar/The Old Man At The Bar - Kyle Young.epub",
		Series: "Else Story",
		StoryExcel: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSGb-gTMRaKc0P_U9PT1i5JNCyveha1Pwz_rSBpWT1IUjO19X7Z4JFrtWXTW21NaayhVsvr7hfNfoNG/pubhtml",
        StoryText: ``,
		ReleaseDate: '2025-10-24',
      },
	  {//The Secret Of Owen Taylor: A Dreamer Story
        Name: "The Secret Of Owen Taylor: A Dreamer Story",
        storytype: "Pages 40 • Short",
        LogoPostions: "Top",
        Genres: ["Myststery", "Adventure", "Thriller", "Fantasy", "Superhero"],
        Forefront: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/poster.png",
        Background: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/background.png",
        LogoStyle1: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/logo_black.svg",
        LogoStyle2: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/logo_white.svg",
        LogoStyle3: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/logo_blue.svg",
        LogoStyle4: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/logo_red.svg",
        LogoStyle5: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/logo_green.svg",
        TitleText: "What the Story is about",
        SmallText: "When a genius billionaire unveils a revolutionary technology, reporter Owen, his best friend, and his girlfriend are caught in the explosion—and they come away with powers.",
        LandscapeImage: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/background.png",
        Pdfstory: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/pdf.pdf",
        Epub: "assets/stories/the_secret_of_owen_taylor_a_dreamer_story/The Secret Of Owen Taylor_ A Dreamer Story - Kyle Young.epub",
        Series: "A Dreamer Story",
		StoryText: ``,
		StoryExcel: "",
		ReleaseDate: '2025-10-24',
      },
	  {//The Last Prank of Tomist
        Name: "The Last Prank of Tomist",
        storytype: "Pages 34 • Short",
        LogoPostions: "Top",
        Genres: ["Kids", "Comedy", "Action", "Adventure", "Coming Of Age", "Family"],
        Forefront: "assets/stories/the_last_prank_of_tomist/poster.png",
        Background: "assets/stories/the_last_prank_of_tomist/background.png",
        LogoStyle1: "assets/stories/the_last_prank_of_tomist/logo_black.svg",
        LogoStyle2: "assets/stories/the_last_prank_of_tomist/logo_white.svg",
        LogoStyle3: "assets/stories/the_last_prank_of_tomist/logo_blue.svg",
        LogoStyle4: "assets/stories/the_last_prank_of_tomist/logo_red.svg",
        LogoStyle5: "assets/stories/the_last_prank_of_tomist/logo_green.svg",
        TitleText: "What the Story is about",
        SmallText: "Leo, a kid who survives a car crash into an alien spaceship, wakes up to find his imaginary friends coming to life.",
        LandscapeImage: "assets/stories/the_last_prank_of_tomist/background.png",
        Pdfstory: "assets/stories/the_last_prank_of_tomist/pdf.pdf",
        Epub: "assets/stories/the_last_prank_of_tomist/The Last Prank of Tomist - Kyle Young.epub",
		Series: "Else Story",
        StoryText: ``,
		ReleaseDate: '2025-10-24',
      },
	  {//Love, Lost And Lost Even More
        Name: "Love Lost And Lost Even More",
        storytype: "Pages 16 • Short",
        LogoPostions: "Top",
        Genres: ["Dark", "Drama", "Adult", "Myststery"],
        Forefront: "assets/stories/love_lost_and_lost_even_more/poster.png",
        Background: "assets/stories/love_lost_and_lost_even_more/background.png",
        LogoStyle1: "assets/stories/love_lost_and_lost_even_more/logo_black.svg",
        LogoStyle2: "assets/stories/love_lost_and_lost_even_more/logo_white.svg",
        LogoStyle3: "assets/stories/love_lost_and_lost_even_more/logo_blue.svg",
        LogoStyle4: "assets/stories/love_lost_and_lost_even_more/logo_red.svg",
        LogoStyle5: "assets/stories/love_lost_and_lost_even_more/logo_green.svg",
        TitleText: "What the Story is about",
        SmallText: "A Coupe Friend Accuse Other Friend Of Rape.",
        LandscapeImage: "assets/stories/love_lost_and_lost_even_more/background.png",
        Pdfstory: "assets/stories/love_lost_and_lost_even_more/pdf.pdf",
        Epub: "assets/stories/love_lost_and_lost_even_more/Love, Lost And Lost Evenmore - Kyle Young.epub",
		Series: "Else Story",
        StoryText: ``,
		StoryExcel: "",
		ReleaseDate: '2025-09-23',
      },
      {//The Forgotten Kingdom
        Name: "The Forgotten Kingdom",
        storytype: "Pages 19 • Short",
        LogoPostions: "Top",
        Genres: ["Dark", "Thriller", "Fantasy", "Myststery"],
        Forefront: "assets/stories/the_forgotten_kingdom/poster.png",
        Background: "assets/stories/the_forgotten_kingdom/background.png",
        LogoStyle1: "assets/stories/the_forgotten_kingdom/logo_black.svg",
        LogoStyle2: "assets/stories/the_forgotten_kingdom/logo_white.svg",
        LogoStyle3: "assets/stories/the_forgotten_kingdom/logo_blue.svg",
        LogoStyle4: "assets/stories/the_forgotten_kingdom/logo_red.svg",
        LogoStyle5: "assets/stories/the_forgotten_kingdom/logo_green.svg",
        TitleText: "What the Story is about",
        SmallText: "When a Legend leave behind a broken kingdom a wizard, a fairy and knight go inside looking for peace.",
        LandscapeImage: "assets/stories/the_forgotten_kingdom/background.png",
        Pdfstory: "assets/stories/the_forgotten_kingdom/pdf.pdf",
		Series: "Else Story",
        Epub: "assets/stories/the_forgotten_kingdom/The Forgotten Kingdom - Kyle Young.epub",
        StoryText: ``,
		StoryExcel: "",
		ReleaseDate: '2025-09-23',
      },
      {//The Puzzle And The Dragon
        Name: "The Puzzle And The Dragon",
        storytype: "Pages 6 • FairyTale",
        LogoPostions: "Top",
        Genres: ["Fairy Tale", "Fantasy", "Kids", "Time-loop", "Romantic"],
        Forefront: "assets/stories/the_puzzle_and_the_dragon/poster.png",
        Mp3: ["assets/stories/the_puzzle_and_the_dragon/chapter_1.mp3", "assets/stories/the_puzzle_and_the_dragon/chapter_2.mp3", "assets/stories/the_puzzle_and_the_dragon/chapter_3.mp3"],
        Background: "assets/stories/the_puzzle_and_the_dragon/Background.png",
        LogoStyle1: "assets/stories/the_puzzle_and_the_dragon/logo_black.svg",
        LogoStyle2: "assets/stories/the_puzzle_and_the_dragon/logo_white.svg",
        LogoStyle3: "assets/stories/the_puzzle_and_the_dragon/logo_blue.svg",
        LogoStyle4: "assets/stories/the_puzzle_and_the_dragon/logo_red.svg",
        LogoStyle5: "assets/stories/the_puzzle_and_the_dragon/logo_green.svg",
        TitleText: "What the Story is about",
        SmallText: "This Story is about time and how it changes people",
        LandscapeImage: "assets/stories/the_puzzle_and_the_dragon/background.png",
        Pdfstory: "assets/stories/the_puzzle_and_the_dragon/pdf.pdf",
		Series: "Else Story",
        Epub: "assets/stories/the_puzzle_and_the_dragon/The Puzzle And The Dragon - Kyle Young.epub",
        StoryText: ``,
		StoryExcel: "",
		ReleaseDate: '2025-09-23',
      },
      {//The Interrogation
        Name: "The Interrogation",
        storytype: "Pages 7 • Short",
        LogoPostions: "Top",
        Genres: ["Psychological", "Thriller", "Crime", "Horror", "Myststery"],
        Forefront: "assets/stories/the_interrogation/poster.png",
        Background: "assets/stories/the_interrogation/background.png",
        LogoStyle1: "assets/stories/the_interrogation/logo_black.svg",
        LogoStyle2: "assets/stories/the_interrogation/logo_white.svg",
        LogoStyle3: "assets/stories/the_interrogation/logo_blue.svg",
        LogoStyle4: "assets/stories/the_interrogation/logo_red.svg",
        LogoStyle5: "assets/stories/the_interrogation/logo_green.svg",
        TitleText: "What the Story is about",
        SmallText: "This Is An Interrogation About Man and Woman Cop",
        LandscapeImage: "assets/stories/the_interrogation/Landscape.png",
        Pdfstory: "assets/stories/the_interrogation/pdf.pdf",
		Series: "Else Story",
        Epub: "assets/stories/the_interrogation/The Interrogation - Kyle Young.epub",
        StoryText: ``,
		StoryExcel: "",
		ReleaseDate: '2025-09-23',
      },
];